ARG NODE_VERSION=20
ARG PHP_EXTENSIONS="mysqli gd pdo_mysql memcached intl apcu hash iconv igbinary mysqlnd redis soap xsl zlib pcov xdebug msgpack"

FROM thecodingmachine/php:8.2-v4-cli-node20

WORKDIR /simpede
