services:
  app:
    build: ./docker/app
    volumes:
      - ../:/workspace:cached
    ports:
      - 80:80
    tty: true
    environment:
      APACHE_DOCUMENT_ROOT: /workspace/public
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: "simpede"
    volumes:
      - "./mariadb/data:/var/lib/mysql/data"
      - "./mariadb/logs:/var/lib/mysql/logs"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - UPLOAD_LIMIT=300M
      - PMA_ARBITARY=1
